const globalAny: any = global;

if (!globalAny.mockUserDB) {
  globalAny.mockUserDB = {
    captain: "hackahoy{ID0R_Capta1n_Secr3t}",
  };
}

export const USER_DB = globalAny.mockUserDB;

export const MISSION_DB: Record<string, any[]> = {
  // 일반 사용자
  user: [
    { id: 1, value: '선체 파손 부위 1차 육안 식별', isChecked: false, status: '진행중' },
    { id: 2, value: '지하 2층 침수 구역 배수 펌프 가동', isChecked: false, status: '진행중' },
    { id: 3, value: '긴급 수리용 목재 확보', isChecked: false, status: '진행중' },
    { id: 4, value: '갑판 위 흩어진 화물 정리', isChecked: false, status: '진행중' },
    { id: 5, value: '구명조끼 수량 재파악', isChecked: false, status: '진행중' },
    { id: 6, value: '찢어진 돛 바느질', isChecked: false, status: '진행중' },
    { id: 7, value: '선장실 문고리 광택 내기', isChecked: false, status: '진행중' },
    { id: 8, value: '암초 파편 수거 및 분석', isChecked: false, status: '진행중' },
    { id: 9, value: '식수 탱크 오염 여부 확인', isChecked: false, status: '진행중' },
    { id: 10, value: '비상 식량 재고 조사', isChecked: false, status: '진행중' },
    { id: 11, value: '녹슨 못 녹 제거 작업', isChecked: false, status: '진행중' },
    { id: 12, value: '조타실 바닥 왁스 칠하기', isChecked: false, status: '진행중' },
    { id: 13, value: '망가진 어망 수선', isChecked: false, status: '진행중' },
    { id: 14, value: '선내 쥐 덫 설치', isChecked: false, status: '진행중' },
    { id: 15, value: '엔진실 기름때 제거', isChecked: false, status: '진행중' },
    { id: 16, value: '부러진 노 교체 작업', isChecked: false, status: '진행중' },
    { id: 17, value: '선원 휴게실 침구류 세탁', isChecked: false, status: '진행중' },
    { id: 18, value: '화장실 배관 막힘 뚫기', isChecked: false, status: '진행중' },
    { id: 19, value: '갑판 위 갈매기 배설물 청소', isChecked: false, status: '진행중' },
    { id: 20, value: '통신 장비 안테나 각도 조절', isChecked: false, status: '진행중' },
    { id: 21, value: '배터리 충전 상태 점검', isChecked: false, status: '진행중' },
    { id: 22, value: '해류 방향 및 속도 매 시간 기록', isChecked: false, status: '진행중' },
    { id: 23, value: '돌섬 주변 수심 측정', isChecked: false, status: '진행중' },
    { id: 24, value: '부상당한 선원 붕대 교체', isChecked: false, status: '진행중' },
    { id: 25, value: '식당 조리도구 설거지', isChecked: false, status: '진행중' },
    { id: 26, value: '창고 내 곰팡이 제거', isChecked: false, status: '진행중' },
    { id: 27, value: '밧줄 매듭 상태 전수 조사', isChecked: false, status: '진행중' },
    { id: 28, value: '선미 쪽 미세 균열 용접', isChecked: false, status: '진행중' },
    { id: 29, value: '조명탄 작동 여부 테스트', isChecked: false, status: '진행중' },
    { id: 30, value: '닻 끌어올리기', isChecked: false, status: '진행중' },
    { id: 31, value: '선장님 전용 낚싯대 손질', isChecked: false, status: '진행중' },
    { id: 32, value: '돌섬의 돌 갯수 세기', isChecked: false, status: '진행중' },
    { id: 33, value: '바닷물 증류해서 소금 만들기', isChecked: false, status: '진행중' },
    { id: 34, value: '낡은 지도 다시 그리기', isChecked: false, status: '진행중' },
    { id: 35, value: '나침반 자성 보정', isChecked: false, status: '진행중' },
    { id: 36, value: '외부 페인트 벗겨진 곳 덧칠', isChecked: false, status: '진행중' },
    { id: 37, value: '소화기 안전 핀 점검', isChecked: false, status: '진행중' },
    { id: 38, value: '비상용 보트 공기 주입', isChecked: false, status: '진행중' },
    { id: 39, value: '선장실 에어컨 필터 청소', isChecked: false, status: '진행중' },
    { id: 40, value: '갑판 틈새 이끼 제거', isChecked: false, status: '진행중' },
    { id: 41, value: '저녁 식사 재료 확보', isChecked: false, status: '진행중' },
    { id: 42, value: '엔진 냉각수 보충', isChecked: false, status: '진행중' },
    { id: 43, value: '기상 상황 라디오 청취 및 보고', isChecked: false, status: '진행중' },
    { id: 44, value: '녹슨 사슬 기름칠', isChecked: false, status: '진행중' },
    { id: 45, value: '함교 유리창 닦기', isChecked: false, status: '진행중' },
    { id: 46, value: '선장님 잃어버린 단추 찾기', isChecked: false, status: '진행중' },
    { id: 47, value: '해안가 떠밀려온 쓰레기 분리수거', isChecked: false, status: '진행중' },
    { id: 48, value: '배 밑바닥 따개비 긁어내기', isChecked: false, status: '진행중' },
    { id: 49, value: '구멍 난 양말 꿰매기', isChecked: false, status: '진행중' },
    { id: 50, value: '하루 일과 보고서 작성', isChecked: false, status: '진행중' },
    { id: 51, value: '주방 식칼 숫돌 연마', isChecked: false, status: '진행중' },
    { id: 52, value: '비상용 신호탄 건조 상태 확인', isChecked: false, status: '진행중' },
    { id: 53, value: '선장님 가발 빗질하기', isChecked: false, status: '진행중' },
    { id: 54, value: '갑판 위 고인 물 퍼내기', isChecked: false, status: '진행중' },
    { id: 55, value: '기록 보관소 문서 먼지 털기', isChecked: false, status: '진행중' },
    { id: 56, value: '망원경 렌즈 닦기', isChecked: false, status: '진행중' },
    { id: 57, value: '예비용 닻 녹 제거', isChecked: false, status: '진행중' },
    { id: 58, value: '선장님 애완 앵무새 말 가르치기', isChecked: false, status: '진행중' },
    { id: 59, value: '조명등 전구 필라멘트 확인', isChecked: false, status: '진행중' },
    { id: 60, value: '선내 방송 마이크 테스트', isChecked: false, status: '진행중' },
    { id: 61, value: '구명정 노 왁스 칠하기', isChecked: false, status: '진행중' },
    { id: 62, value: '선장님 장화 광내기', isChecked: false, status: '진행중' },
    { id: 63, value: '바다 위 떠다니는 나무판자 수거', isChecked: false, status: '진행중' },
    { id: 64, value: '선내 소화전 호스 꼬임 풀기', isChecked: false, status: '진행중' },
    { id: 65, value: '엔진룸 환풍구 청소', isChecked: false, status: '진행중' },
    { id: 66, value: '선장님 저녁 반찬용 미역 채취', isChecked: false, status: '진행중' },
    { id: 67, value: '녹슨 나사 크기별 분류', isChecked: false, status: '진행중' },
    { id: 68, value: '의무실 약품 유통기한 전수 조사', isChecked: false, status: '진행중' },
    { id: 69, value: '함교 바닥 카펫 먼지 제거', isChecked: false, status: '진행중' },
    { id: 70, value: '레이더 화면 얼룩 닦기', isChecked: false, status: '진행중' },
    { id: 71, value: '선미 깃발 다림질', isChecked: false, status: '진행중' },
    { id: 72, value: '조리실 냉장고 성에 제거', isChecked: false, status: '진행중' },
    { id: 73, value: '선장님 찻잔 세트 세척', isChecked: false, status: '진행중' },
    { id: 74, value: '비상 발전기 연료 확인', isChecked: false, status: '진행중' },
    { id: 75, value: '선내 모든 시계 시간 동기화', isChecked: false, status: '진행중' },
    { id: 76, value: '갑판 난간 페인트칠', isChecked: false, status: '진행중' },
    { id: 77, value: '구명 튜브 공기압 체크', isChecked: false, status: '진행중' },
    { id: 78, value: '선장님 낮잠용 해먹 설치', isChecked: false, status: '진행중' },
    { id: 79, value: '조타기 기름칠', isChecked: false, status: '진행중' },
    { id: 80, value: '엔진 소음 데시벨 측정', isChecked: false, status: '진행중' },
    { id: 81, value: '선내 모든 전등 스위치 점검', isChecked: false, status: '진행중' },
    { id: 82, value: '바닥 타일 깨진 곳 보수', isChecked: false, status: '진행중' },
    { id: 83, value: '선장님 안경 닦기', isChecked: false, status: '진행중' },
    { id: 84, value: '식당 테이블 껌 떼기', isChecked: false, status: '진행중' },
    { id: 85, value: '화물칸 재고 목록 수기 정리', isChecked: false, status: '진행중' },
    { id: 86, value: '선체 외부 해조류 제거', isChecked: false, status: '진행중' },
    { id: 87, value: '선장님 곰인형 세탁', isChecked: false, status: '진행중' },
    { id: 88, value: '비상용 손전등 건전지 교체', isChecked: false, status: '진행중' },
    { id: 89, value: '통로 안전 표지판 닦기', isChecked: false, status: '진행중' },
    { id: 90, value: '갑판 배수로 낙엽 청소', isChecked: false, status: '진행중' },
    { id: 91, value: '선장님 일기장 표지 닦기', isChecked: false, status: '진행중' },
    { id: 92, value: '엔진 피스톤 마모도 확인', isChecked: false, status: '진행중' },
    { id: 93, value: '선내 모든 열쇠 짝 맞추기', isChecked: false, status: '진행중' },
    { id: 94, value: '구름 모양 관찰 일지 작성', isChecked: false, status: '진행중' },
    { id: 95, value: '선장님 간식용 코코넛 깨기', isChecked: false, status: '진행중' },
    { id: 96, value: '함교 의자 높낮이 조절', isChecked: false, status: '진행중' },
    { id: 97, value: '선미 방향타 수중 점검', isChecked: false, status: '진행중' },
    { id: 98, value: '선내 습도 조절을 위한 숯 배치', isChecked: false, status: '진행중' },
    { id: 99, value: '돌섬 모래알 크기별 분류', isChecked: false, status: '진행중' },
    { id: 100, value: '이 모든 임무를 다시 처음부터 검토', isChecked: false, status: '진행중' },
  ],
  // flag 노출
  captain: [
    { id: 1, value: '끝내주는 낮잠 자기', isChecked: false, status: '진행중' },
    { id: 2, value: 'hackahoy{ID0R_Capta1n_Secr3t}', isChecked: false, status: '진행중' }, // 플래그 노출
  ],
};